### PR TITLE
make react hook forms defaultValues property accessible

### PR DESCRIPTION
**Pull request by luckals**
I want to use react hook forms defaultValues property like its described here:
https://react-hook-form.com/api/useform/

If the default values are defined this way the dirty field status works even better: If the user changes a fields value from the default value to a new value and then back to the default value, the form is not dirty anymore. Without the defaultValues it would be still dirty.

This pr also helps to provide default values easier than via zod schema.
`<Form schema={schema} method="patch" defaultValues={{email: 'amdin@example.com', firstName: 'Mary'}}>`

### CODE REVIEW

**Comment by moishinetzer** [comment]
I'm sorry I did not clarify, however this fix doesn't specifically fix #40 as I was not clear enough with the specific use case. 

I tried with this pr and it did not fix my specific scenario.

**Important:** I did test this on my machine and the desired effects of defaultValues WAS applied, so this specific PR works just fine for me for what it sets out to resolve.

**Comment by luckals** [comment]
@moishinetzer Thank you for testing it! I understood your issue more generally.

**Comment by paulm17** [comment]
I was having a real head scratcher wondering why custom components where not being updated, when using controller.

I totally forgot about defaultValues, once I applied this PR myself.  Controller started accepting the value from onChange.

**Comment by moishinetzer** [comment]
@paulm17 I'm struggling with this use case, do you have any examples where you have used this?

**Comment by paulm17** [comment]
@moishinetzer Of course, happy to help.

Here is a quick mock up of the relevant parts.

https://gist.githubusercontent.com/paulm17/4b5a0f535f6912beb482dad3ff07a757/raw/183f02487388757c8bfd020153069b9dfb99f716/gistfile1.txt

**Comment by luckals** [comment]
I would really like to see the defaultValue feature in this package. When I created this pr, no file conflicts appeared. Now, after two weeks and some other updates in the package, a file conflict showed up. 

Should I update the code for this pr?

**Comment by gustavoguichard** [comment]
Hey @luckals , sorry for the lack of answers. We've been working on improving the overall DX of this library and bringing the website docs into this repo through turborepo.
The good news tough is that we just moved the library files from `./src` to `./packages/remix-forms/src` so the rebase should be easy stuff.

Now that we are happy with the DX and we have good test coverage we'll be confident to review and merge the open PRs ;)

**Comment by diogob** [comment]
@luckals we are going to relay the property `values` to `defaultValues`, so the defaults for `remix-forms` are consistent with the form state of the underlying `react-hook-form`. This would not expose the prop for `react-hook-form` but it seems to fit your use case, is that right?

**Comment by diogob** [comment]
will close this in favour of #98

**Pull request closed without merging**
