### PR TITLE
Fix falsy form values and add edit values example

### LINKED ISSUE #38: Fields with value equal to `0` are shown as empty
Here is a code example:

```ts
const schema = z.object({
  _method: z.literal('drop-time'),
  index: z.number().int(),
})

<Form
  schema={schema}
  method="post"
  values={{
    _method: 'drop-time',
    index: 0
  }}
/>
```

### PR DESCRIPTION
**Pull request by danielweinmann**
This fixes #38

### CODE REVIEW

**Review by andrepinho — APPROVED** [review]
LGTM!

Only minor problem I found probably should be a different issue/PR:
image

It's not `nan`, it's a string.

**Review by gustavoguichard — APPROVED** [review]
LGTM

**Comment by gustavoguichard** [comment]
@andrepinho , would you register that issue please?

**Comment by andrepinho** [comment]
> @andrepinho , would you register that issue please?

Here it is @gustavoguichard https://github.com/SeasonedSoftware/remix-forms/issues/60

**Pull request merged**
